import argparse
from framework.SQA import *
from framework.ReSeg import *

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--frames_path', type=str, default='./example/frames')
    parser.add_argument('--origin_masks_path', type=str, default='./example/origin_masks', help='masks generated by segmentation model')
    parser.add_argument('--SQA_scores_path', type=str, default='./example/SQA_score.json')
    parser.add_argument('--reseg_masks_path', type=str, default='./example/reseg_masks')
    parser.add_argument('--radius', type=int, default=10, help='spatiotemporal window radius')
    parser.add_argument('--threshold', type=float, default=0.85, help='selection of reliable scores')
    parser.add_argument('--reseg_num', type=int, default=6, help='the number of high-quality frames used for re-segmentation')
    opt = parser.parse_args()

    if not os.path.exists("./temp"):
        os.mkdir("./temp")
    prop_videos_path = "./temp/prop_videos"  # temporary storage of intermediate results
    propagations_path = "./temp/prop_masks"

    make_dirs([prop_videos_path, propagations_path, opt.reseg_masks_path])

    create_videos(opt.frames_path, prop_videos_path, opt.radius)
    propagate(opt, prop_videos_path, propagations_path)
    print("Successfully propagated")

    calc_SQA(opt, propagations_path)
    print("Successfully assessed segmentation quality")

    ReSeg(opt, propagations_path)
    print("Successfully re-segmented")
    destroy_dirs(["./temp"])
